# Flake8: noqa

LLM_REQUEST_TIMEOUT = 300

MAX_SQL_LENGTH = 10000

SUPPORTED_DB_TYPES = ["postgresql", "mysql", "sqlite"]

LOCALHOSTS = ['localhost', '127.0.0.1']

AUTH_PROVIDER_EMAIL = 'email'
AUTH_PROVIDER_GOOGLE = 'google'

GOOGLE_OAUTH_METADATA_URL = 'https://accounts.google.com/.well-known/openid-configuration'
GOOGLE_OAUTH_SCOPES = 'openid email profile'

MOCK_DATA_RECURSION_MAX_DEPTH = 3
MOCK_DATA_AUTO_PARENT_ROWS = 10
MOCK_DATA_DEFAULT_LOCALE = 'en_US'

MOCK_DATA_AGE_MIN = 18
MOCK_DATA_AGE_MAX = 80

MOCK_DATA_PRICE_MIN = 10
MOCK_DATA_PRICE_MAX = 10000

MOCK_DATA_INT_MIN = 0
MOCK_DATA_INT_MAX = 1000

MOCK_DATA_SMALLINT_MAX = 100
MOCK_DATA_BIGINT_MAX = 100000
MOCK_DATA_TINYINT_MAX = 10
MOCK_DATA_SERIAL_MIN = 1

MOCK_DATA_FLOAT_MIN = 0
MOCK_DATA_FLOAT_MAX = 1000

MOCK_DATA_MONEY_MAX = 10000
MOCK_DATA_DESCRIPTION_MAX_CHARS = 200
MOCK_DATA_TITLE_WORDS = 6
MOCK_DATA_TEXT_SHORT_SENTENCES = 3
MOCK_DATA_TEXT_LONG_SENTENCES = 5
MOCK_DATA_BINARY_LENGTH = 16

MOCK_DATA_VARCHAR_SHORT_THRESHOLD = 15
MOCK_DATA_VARCHAR_DEFAULT_MAX = 100
MOCK_DATA_VARCHAR_ABSOLUTE_MAX = 200
